{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "10b0b756",
   "metadata": {},
   "source": [
    "Reference: \n",
    "- [Kaggle1](https://www.kaggle.com/yamqwe/crypto-prediction-xgb-regressor)\n",
    "- [Kaggle2](https://www.kaggle.com/tensorchoko/g-research-for-jp-en-coins)\n",
    "- [Official doc](https://xgboost.readthedocs.io/en/latest/python/index.html)\n",
    "- [https://mljar.com/blog/xgboost-save-load-python/](https://mljar.com/blog/xgboost-save-load-python/)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "0b5df544",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2021-11-29T11:42:23.096103Z",
     "iopub.status.busy": "2021-11-29T11:42:23.095321Z",
     "iopub.status.idle": "2021-11-29T11:42:25.913271Z",
     "shell.execute_reply": "2021-11-29T11:42:25.913730Z",
     "shell.execute_reply.started": "2021-11-04T09:37:03.772987Z"
    },
    "papermill": {
     "duration": 2.840833,
     "end_time": "2021-11-29T11:42:25.913990",
     "exception": false,
     "start_time": "2021-11-29T11:42:23.073157",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.5.0\n"
     ]
    }
   ],
   "source": [
    "import IPython.display\n",
    "import traceback\n",
    "import gc\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import datatable as dt\n",
    "import lightgbm as lgb\n",
    "from lightgbm import LGBMRegressor\n",
    "import xgboost as xgb\n",
    "print(xgb.__version__)\n",
    "import talib as ta\n",
    "\n",
    "\n",
    "TRAIN_JAY = './data/cryptocurrency-extra-data-binance-coin/orig_train.jay'\n",
    "ASSET_DETAILS_JAY = './data/cryptocurrency-extra-data-binance-coin/orig_asset_details.jay'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "id": "3ab83e47",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2021-11-29T11:42:25.938912Z",
     "iopub.status.busy": "2021-11-29T11:42:25.938198Z",
     "iopub.status.idle": "2021-11-29T11:42:45.696951Z",
     "shell.execute_reply": "2021-11-29T11:42:45.696426Z",
     "shell.execute_reply.started": "2021-11-04T09:37:03.781684Z"
    },
    "papermill": {
     "duration": 19.772243,
     "end_time": "2021-11-29T11:42:45.697110",
     "exception": false,
     "start_time": "2021-11-29T11:42:25.924867",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "df_train = dt.fread('./data/cryptocurrency-extra-data-binance-coin/orig_train.jay').to_pandas()\n",
    "df_asset_details = dt.fread('./data/cryptocurrency-extra-data-binance-coin/orig_asset_details.jay').to_pandas().sort_values(\"Asset_ID\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "id": "4a7308cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "#VWAP make finite\n",
    "VWAP_max = np.max(df_train[np.isfinite(df_train.VWAP)].VWAP)\n",
    "VWAP_min = np.min(df_train[np.isfinite(df_train.VWAP)].VWAP)\n",
    "df_train['VWAP'] = np.nan_to_num(df_train.VWAP, posinf=VWAP_max, neginf=VWAP_min)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5c5ac6f3",
   "metadata": {
    "papermill": {
     "duration": 0.010875,
     "end_time": "2021-11-29T11:42:45.761005",
     "exception": false,
     "start_time": "2021-11-29T11:42:45.750130",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "## Utility functions to train a model for one asset"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f8d5fe31",
   "metadata": {
    "papermill": {
     "duration": 0.009087,
     "end_time": "2021-11-29T11:42:45.903563",
     "exception": false,
     "start_time": "2021-11-29T11:42:45.894476",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "**Main Training Function**, **Feature Extraction**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "id": "37cb6684",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2021-11-29T11:42:45.929823Z",
     "iopub.status.busy": "2021-11-29T11:42:45.925915Z",
     "iopub.status.idle": "2021-11-29T11:42:45.932345Z",
     "shell.execute_reply": "2021-11-29T11:42:45.931858Z",
     "shell.execute_reply.started": "2021-11-04T09:37:50.959993Z"
    },
    "papermill": {
     "duration": 0.019564,
     "end_time": "2021-11-29T11:42:45.932464",
     "exception": false,
     "start_time": "2021-11-29T11:42:45.912900",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Memory usage of dataframe is 1849.12 MB\n",
      "int64->int32\n",
      "int64->int8\n",
      "float64->float32\n",
      "float64->float32\n",
      "float64->float32\n",
      "float64->float32\n",
      "float64->float32\n",
      "float64->float32\n",
      "float64->float32\n",
      "float64->float32\n",
      "Memory usage after optimization is: 855.22 MB\n",
      "Decreased by 53.7%\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "255"
      ]
     },
     "execution_count": 66,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from script.XGB.xgbmodel import *\n",
    "# Memory saving function credit to https://www.kaggle.com/gemartin/load-data-reduce-memory-usage\n",
    "def reduce_mem_usage(df):\n",
    "    \"\"\" \n",
    "        iterate through all the columns of a dataframe and modify the data type\n",
    "        to reduce memory usage.\n",
    "    \"\"\"\n",
    "    start_mem = df.memory_usage().sum() / 1024**2\n",
    "    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))\n",
    "\n",
    "    for col in df.columns:\n",
    "        col_type = df[col].dtype.name\n",
    "        \n",
    "        if col_type not in ['object', 'category', 'datetime64[ns, UTC]', 'datetime64[ns]']:\n",
    "            c_min = df[col].min()\n",
    "            c_max = df[col].max()\n",
    "            if str(col_type)[:3] == 'int':\n",
    "                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:\n",
    "                    df[col] = df[col].astype(np.int8)\n",
    "                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:\n",
    "                    df[col] = df[col].astype(np.int16)\n",
    "                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:\n",
    "                    df[col] = df[col].astype(np.int32)\n",
    "                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:\n",
    "                    df[col] = df[col].astype(np.int64)  \n",
    "            else:\n",
    "                if c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:\n",
    "                    df[col] = df[col].astype(np.float32)\n",
    "                elif c_min > np.finfo(np.float64).min and c_max < np.finfo(np.float64).max:\n",
    "                    df[col] = df[col].astype(np.float64)\n",
    "                else:\n",
    "                    next\n",
    "        print(f'{col_type}->{df[col].dtype.name}')\n",
    "\n",
    "    end_mem = df.memory_usage().sum() / 1024**2\n",
    "    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))\n",
    "    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))\n",
    "\n",
    "    return df\n",
    "\n",
    "df_train= reduce_mem_usage(df_train)\n",
    "gc.collect()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c0acb77c",
   "metadata": {
    "papermill": {
     "duration": 0.009251,
     "end_time": "2021-11-29T11:42:45.951347",
     "exception": false,
     "start_time": "2021-11-29T11:42:45.942096",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "## Loop over all assets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "id": "a08f97ec",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2021-11-29T11:42:45.977783Z",
     "iopub.status.busy": "2021-11-29T11:42:45.976878Z",
     "iopub.status.idle": "2021-11-29T16:31:57.306788Z",
     "shell.execute_reply": "2021-11-29T16:31:57.306268Z",
     "shell.execute_reply.started": "2021-11-04T09:37:50.972645Z"
    },
    "papermill": {
     "duration": 17351.346119,
     "end_time": "2021-11-29T16:31:57.306942",
     "exception": false,
     "start_time": "2021-11-29T11:42:45.960823",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "model for Binance Coin     (ID=0 ) exists\n",
      "model for Bitcoin          (ID=1 ) exists\n",
      "model for Bitcoin Cash     (ID=2 ) exists\n",
      "model for Cardano          (ID=3 ) exists\n",
      "model for Dogecoin         (ID=4 ) exists\n",
      "model for EOS.IO           (ID=5 ) exists\n",
      "model for Ethereum         (ID=6 ) exists\n",
      "model for Ethereum Classic (ID=7 ) exists\n",
      "model for IOTA             (ID=8 ) exists\n",
      "model for Litecoin         (ID=9 ) exists\n",
      "model for Maker            (ID=10) exists\n",
      "model for Monero           (ID=11) exists\n",
      "model for Stellar          (ID=12) exists\n",
      "model for TRON             (ID=13) exists\n"
     ]
    }
   ],
   "source": [
    "from os.path import exists\n",
    "Xs = {}\n",
    "ys = {}\n",
    "models = {}\n",
    "\n",
    "for asset_id, asset_name in zip(df_asset_details['Asset_ID'], df_asset_details['Asset_Name']):\n",
    "    \n",
    "    if exists(f\"./trainedXGB/XGB1/model_{asset_id}.txt\"):\n",
    "        print(f\"model for {asset_name:<16} (ID={asset_id:<2}) exists\")\n",
    "        ## for xgbregressor0\n",
    "        # model = xgb.XGBRegressor()\n",
    "        # model.load_model(f\"./trainedXGB/XGB0/model_{asset_id}.json\")\n",
    "        \n",
    "        # df = df_train[df_train[\"Asset_ID\"] == asset_id]\n",
    "        # df_proc = get_features(df)\n",
    "        \n",
    "        # df_proc['y'] = df['Target']\n",
    "        # df_proc = df_proc.dropna(how=\"any\")\n",
    "        # X = df_proc.drop(\"y\", axis=1)\n",
    "        # y = df_proc[\"y\"]\n",
    "        \n",
    "        ## for lightgbm1\n",
    "        model = lgb.Booster(model_file=f\"./trainedXGB/XGB1/model_{asset_id}.txt\")\n",
    "        df = df_train[df_train[\"Asset_ID\"] == asset_id]\n",
    "        df = df.dropna(subset=['Target'])\n",
    "        y = df['Target'] \n",
    "        df = df.drop(['Target'],axis=1)\n",
    "        df_proc = get_features(df)\n",
    "        df_proc = add_features(df_proc)\n",
    "        df_proc = df_proc.fillna(-1)\n",
    "        df_proc = df_proc.drop(['timestamp', 'Asset_ID','hour','dayofweek', 'day'],axis=1)\n",
    "        X= df_proc \n",
    "\n",
    "        Xs[asset_id], ys[asset_id], models[asset_id] = X, y, model\n",
    "        next\n",
    "    else:\n",
    "        print(f\"Training model for {asset_name:<16} (ID={asset_id:<2})\")\n",
    "        try:\n",
    "            X, y, model = get_Xy_and_model_for_asset_1(df_train, asset_id)    \n",
    "            Xs[asset_id], ys[asset_id], models[asset_id] = X, y, model\n",
    "        except:         \n",
    "            Xs[asset_id], ys[asset_id], models[asset_id] = None, None, None    \n",
    "        #save model\n",
    "        models[asset_id].booster_.save_model(f\"./trainedXGB/XGB1/model_{asset_id}.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "id": "e6f474b0",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2021-11-29T16:31:57.345401Z",
     "iopub.status.busy": "2021-11-29T16:31:57.342354Z",
     "iopub.status.idle": "2021-11-29T16:31:57.351781Z",
     "shell.execute_reply": "2021-11-29T16:31:57.352251Z",
     "shell.execute_reply.started": "2021-11-04T09:41:28.043037Z"
    },
    "papermill": {
     "duration": 0.031939,
     "end_time": "2021-11-29T16:31:57.352418",
     "exception": false,
     "start_time": "2021-11-29T16:31:57.320479",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/pandas/core/series.py:1056: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  cacher_needs_updating = self._check_is_chained_assignment_possible()\n",
      "/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/pandas/core/indexing.py:1724: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  self._setitem_with_indexer_missing(indexer, value)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "-0.036999944382306124"
      ]
     },
     "execution_count": 68,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Check the model interface\n",
    "x = get_features(df_train.iloc[1])\n",
    "x=pd.DataFrame([x])\n",
    "x = add_features(x)\n",
    "x = x.fillna(-1)\n",
    "x = x.drop(['timestamp', 'Asset_ID','hour','dayofweek', 'day','Target'],axis=1)\n",
    "y_pred = models[0].predict(x)\n",
    "y_pred[0]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e140ddbf",
   "metadata": {},
   "source": [
    "## Submit to Kaggle Lightxgb\n",
    "\n",
    "- attached with previous data(x_prior)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "id": "4734c71f",
   "metadata": {},
   "outputs": [],
   "source": [
    "data_path = './data/'\n",
    "train = pd.read_csv(data_path+'/train.csv').set_index('timestamp')\n",
    "WINDOW_SIZE = 100\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "id": "72beb402",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1385, 9)\n",
      "(1441, 9)\n",
      "    row_id    Target  row_id    Target  row_id    Target  row_id    Target\n",
      "0        0 -0.014661      14 -0.005366      28 -0.001190      42 -0.012154\n",
      "1        1  0.005207      15 -0.005224      29  0.003402      43  0.001301\n",
      "2        2 -0.040518      16 -0.011133      30 -0.020008      44 -0.028566\n",
      "3        3  0.004674      17 -0.001437      31 -0.003973      45 -0.005514\n",
      "4        4 -0.029864      18 -0.027143      32 -0.043370      46 -0.055095\n",
      "5        5 -0.005070      19 -0.011641      33 -0.013088      47 -0.022040\n",
      "6        6  0.028932      20  0.011306      34 -0.007918      48 -0.025200\n",
      "7        7 -0.001971      21  0.001072      35 -0.000579      49 -0.004929\n",
      "8        8 -0.022743      22 -0.038666      36 -0.045859      50 -0.054999\n",
      "9        9 -0.008685      23 -0.003194      37 -0.000035      51 -0.003864\n",
      "10      10 -0.029130      24 -0.028767      38 -0.028118      52 -0.033359\n",
      "11      11 -0.023421      25 -0.026586      39 -0.028743      53 -0.027078\n",
      "12      12 -0.019559      26 -0.022414      40 -0.021665      54 -0.033427\n",
      "13      13 -0.050220      27 -0.030804      41 -0.056316      55 -0.076889\n"
     ]
    }
   ],
   "source": [
    "submission = []\n",
    "for i in range(4):\n",
    "    test_csv,sample_prediction_df_csv = f'{data_path}kagglesubmission/{i}test_df.csv', f'{data_path}kagglesubmission/{i}sample_prediction_df.csv'\n",
    "    df_test, df_pred= pd.read_csv(test_csv,usecols =range(1,11)),pd.read_csv(sample_prediction_df_csv,usecols =range(1,3))\n",
    "    if i ==0:\n",
    "        #add placeholder\n",
    "        ts_last = df_test['timestamp'].unique().item()\n",
    "        ts_placeholder = list(range(ts_last-60*(WINDOW_SIZE-1),ts_last, 60))\n",
    "        placeholder = train.loc[ts_placeholder,:].reset_index() #previous sample\n",
    "        placeholder = placeholder.drop('Target',axis =1)\n",
    "        print(placeholder.shape)\n",
    "    for j , row in df_test.iterrows():\n",
    "        if models[row['Asset_ID']] is not None:\n",
    "            try:\n",
    "                x_prior = placeholder.loc[placeholder['Asset_ID']==row['Asset_ID'],:]#99X9\n",
    "                x_test = x_prior.append(row[x_prior.columns])\n",
    "                placeholder = placeholder.append(row[placeholder.columns])#add to placeholder\n",
    "\n",
    "                x_test = get_features(x_test)\n",
    "                x_test = add_features(x_test)\n",
    "                x_test = x_test.fillna(-1)\n",
    "                x_test = x_test.drop(['timestamp', 'Asset_ID','hour','dayofweek', 'day'],axis=1)\n",
    "\n",
    "                model = models[row['Asset_ID']]\n",
    "                y_pred = model.predict(x_test.iloc[-2:,:]) #100\n",
    "                df_pred.loc[df_pred['row_id'] == row['row_id'], 'Target'] = y_pred[-1]\n",
    "            except:\n",
    "                \n",
    "                df_pred.loc[df_pred['row_id'] == row['row_id'], 'Target'] = 0\n",
    "                traceback.print_exc()\n",
    "        else: \n",
    "            df_pred.loc[df_pred['row_id'] == row['row_id'], 'Target'] = 0\n",
    "    submission.append(df_pred)\n",
    "print(placeholder.shape)\n",
    "print(pd.concat(submission,axis=1))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e4176c24",
   "metadata": {
    "execution": {
     "iopub.status.busy": "2021-11-02T20:57:49.349459Z",
     "iopub.status.idle": "2021-11-02T20:57:49.349757Z",
     "shell.execute_reply": "2021-11-02T20:57:49.349613Z",
     "shell.execute_reply.started": "2021-11-02T20:57:49.349596Z"
    },
    "papermill": {
     "duration": 0.01424,
     "end_time": "2021-11-29T16:31:57.382398",
     "exception": false,
     "start_time": "2021-11-29T16:31:57.368158",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Submit To Kaggle XGBoost"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "id": "29a7d4af",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2021-11-29T16:31:57.419470Z",
     "iopub.status.busy": "2021-11-29T16:31:57.418889Z",
     "iopub.status.idle": "2021-11-29T16:31:57.701929Z",
     "shell.execute_reply": "2021-11-29T16:31:57.702479Z",
     "shell.execute_reply.started": "2021-11-04T09:41:42.957395Z"
    },
    "papermill": {
     "duration": 0.305764,
     "end_time": "2021-11-29T16:31:57.702653",
     "exception": false,
     "start_time": "2021-11-29T16:31:57.396889",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3.0\n",
      "2.0\n",
      "0.0\n",
      "1.0\n",
      "4.0\n",
      "5.0\n",
      "7.0\n",
      "6.0\n",
      "8.0\n",
      "9.0\n",
      "10.0\n",
      "13.0\n",
      "12.0\n",
      "11.0\n",
      "3.0\n",
      "2.0\n",
      "0.0\n",
      "1.0\n",
      "4.0\n",
      "5.0\n",
      "7.0\n",
      "6.0\n",
      "8.0\n",
      "9.0\n",
      "10.0\n",
      "13.0\n",
      "12.0\n",
      "11.0\n",
      "3.0\n",
      "2.0\n",
      "0.0\n",
      "1.0\n",
      "4.0\n",
      "5.0\n",
      "7.0\n",
      "6.0\n",
      "8.0\n",
      "9.0\n",
      "10.0\n",
      "13.0\n",
      "12.0\n",
      "11.0\n",
      "3.0\n",
      "2.0\n",
      "0.0\n",
      "1.0\n",
      "4.0\n",
      "5.0\n",
      "7.0\n",
      "6.0\n",
      "8.0\n",
      "9.0\n",
      "10.0\n",
      "13.0\n",
      "12.0\n",
      "11.0\n",
      "    row_id  Target  row_id  Target  row_id  Target  row_id  Target\n",
      "0        0     0.0      14     0.0      28     0.0      42     0.0\n",
      "1        1     0.0      15     0.0      29     0.0      43     0.0\n",
      "2        2     0.0      16     0.0      30     0.0      44     0.0\n",
      "3        3     0.0      17     0.0      31     0.0      45     0.0\n",
      "4        4     0.0      18     0.0      32     0.0      46     0.0\n",
      "5        5     0.0      19     0.0      33     0.0      47     0.0\n",
      "6        6     0.0      20     0.0      34     0.0      48     0.0\n",
      "7        7     0.0      21     0.0      35     0.0      49     0.0\n",
      "8        8     0.0      22     0.0      36     0.0      50     0.0\n",
      "9        9     0.0      23     0.0      37     0.0      51     0.0\n",
      "10      10     0.0      24     0.0      38     0.0      52     0.0\n",
      "11      11     0.0      25     0.0      39     0.0      53     0.0\n",
      "12      12     0.0      26     0.0      40     0.0      54     0.0\n",
      "13      13     0.0      27     0.0      41     0.0      55     0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "[LightGBM] [Fatal] The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/_0/sgv1wmb92l11hndgfl0tyvjr0000gn/T/ipykernel_44551/3870017929.py\", line 11, in <module>\n",
      "    y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 3538, in predict\n",
      "    return predictor.predict(data, start_iteration, num_iteration,\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 848, in predict\n",
      "    preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 938, in __pred_for_np2d\n",
      "    return inner_predict(mat, start_iteration, num_iteration, predict_type)\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 908, in inner_predict\n",
      "    _safe_call(_LIB.LGBM_BoosterPredictForMat(\n",
      "  File \"/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/lightgbm/basic.py\", line 125, in _safe_call\n",
      "    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))\n",
      "lightgbm.basic.LightGBMError: The number of features in data (12) is not the same as it was in training data (36).\n",
      "You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.\n"
     ]
    }
   ],
   "source": [
    "data_path = './data/'\n",
    "submission = []\n",
    "for i in range(4):\n",
    "    test_csv,sample_prediction_df_csv = f'{data_path}kagglesubmission/{i}test_df.csv', f'{data_path}kagglesubmission/{i}sample_prediction_df.csv'\n",
    "    df_test, df_pred= pd.read_csv(test_csv,usecols =range(1,11)),pd.read_csv(sample_prediction_df_csv,usecols =range(1,3))\n",
    "    for j , row in df_test.iterrows():\n",
    "        if models[row['Asset_ID']] is not None:\n",
    "            try:\n",
    "                model = models[row['Asset_ID']]\n",
    "                x_test = get_features(row)\n",
    "                y_pred = model.predict(pd.DataFrame([x_test]))[0]\n",
    "                df_pred.loc[df_pred['row_id'] == row['row_id'], 'Target'] = y_pred\n",
    "            except:\n",
    "                print(row['Asset_ID'])\n",
    "                df_pred.loc[df_pred['row_id'] == row['row_id'], 'Target'] = 0\n",
    "                traceback.print_exc()\n",
    "        else: \n",
    "            df_pred.loc[df_pred['row_id'] == row['row_id'], 'Target'] = 0\n",
    "    submission.append(df_pred)\n",
    "\n",
    "print(pd.concat(submission,axis=1))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7774ef63",
   "metadata": {},
   "source": [
    "## Scores"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a582c409",
   "metadata": {
    "papermill": {
     "duration": 0.013408,
     "end_time": "2021-11-29T16:31:57.731153",
     "exception": false,
     "start_time": "2021-11-29T16:31:57.717745",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 17383.268184,
   "end_time": "2021-11-29T16:31:58.883382",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2021-11-29T11:42:15.615198",
   "version": "2.3.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
